name: Pale Blue Dot
description: everettjf's blog
meta_description: "I'm everettjf & iOS/macOS/Windows Developer & interested in Reverse Engineering"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: 'http://everettjf.com/'
domain_name: 'http://everettjf.com'
google_analytics: 'UA-111349332-1'
plugins:
  - jekyll-paginate

# Details for the RSS feed generator
url:            'http://everettjf.com'
author:         'everettjf'
authorimage: /images/everettjf.png

permalink: /:year/:month/:day/:title/
location: 'Beijing, China'
