name: Pale Blue Dot
description: Reverse Engineering
meta_description: "I am everettjf iOS/macOS/Windows Developer Interested in Reverse Engineering"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://everettjf.com'
google_analytics: 'UA-111349332-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://everettjf.com'
author:         'everettjf'
authorimage: /images/everettjf.png

permalink: /:year/:month/:day/:title/
location: 'Beijing, China'
